#08.09.2018:test server in aws only support version 2
version: '2'
services:
  db:
    image: "postgres:9.6.9"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_network
  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  nginx:
    image: "nginx:1.13.12"
    ports:
      #08.09.2018:port 4040 is opened in the terraform already, so using that
      - "4040:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flaskapp
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata:
